### ISSUE TITLE
lmao

### ISSUE THREAD

**Issue by sabaasa** [craftablescience/VPKEdit#8]
![image](https://github.com/craftablescience/VPKEdit/assets/75037904/29dd3120-e98c-4aa9-9062-7f1a947542de)

**Comment by sabaasa** [comment]
standalone version works 👍🏻

**Comment by sabaasa** [comment]
![image](https://github.com/craftablescience/VPKEdit/assets/75037904/cb59d81a-84c5-4275-9367-40397662f1b9)

**Comment by craftablescience** [comment]
Woops, forgot to add the network library to the installers
Fixed in c35f2413af5323e92cd409e0f1b800fec3f5d539 (I've updated the 3.3.0 release)

**Comment by sabaasa** [comment]
all good xd, I was just looking for a way to look into .vpk files and such 

offtopic question but will there be a model viewer in vpkedit at some point?

**Comment by craftablescience** [comment]
I'm planning on it yep! It won't look as good as the preview in Hammer since I'm not going to use the source engine to render them, but it would be nice to have some kind of model preview

**Comment by sabaasa** [comment]
> I'm planning on it yep! It won't look as good as the preview in Hammer since I'm not going to use the source engine to render them, but it would be nice to have some kind of model preview

do you have any idea why checking for updates doesnt work? i redownloaded vpkedit and it still doesnt work seemingly, just says "error occured when checking for updates"
is that supposed to happen if no newer updates are present or?

**Comment by craftablescience** [comment]
Sorry, I forgot to modify the GitHub actions file to bundle the tls plugins, I'll fix that now

**Comment by sabaasa** [comment]
you seem to forget a lot of things silly

**Comment by craftablescience** [comment]
Updated the 3.3.0 release, it should include the necessary stuff in the standalone versions now
